name=PWM
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Pulse Width Modulation library for Beken boards
paragraph=Provides Pulse Width Modulation (PWM) capabilities for generating variable duty cycle signals on supported pins.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n