name=GPIO
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=General Purpose Input/Output library for Beken boards
paragraph=Provides digital pin control capabilities for configuring and controlling GPIO pins on Beken microcontrollers.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n