name=Websocket
version=0.6.0
author=Arduino
maintainer=BK-IDK
sentence=[EXPERIMENTAL] HTTP and WebSocket client for arduino-beken.
paragraph=HTTP and WebSocket client for Beken arduino-beken (BK7239N), based on ArduinoHttpClient. Use WiFiClient for ws:// or WiFiClientSecure for wss://.
category=Communication
includes=Websocket.h
architectures=bk7239n
depends=WiFi,WiFiClientSecure
