name=Timer
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Timer library for Beken boards
paragraph=Provides timer and timing capabilities for scheduling events, measuring intervals, and managing time-based operations.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n