name=Wire
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=I2C communication library for Beken boards
paragraph=Provides Inter-Integrated Circuit (I2C) communication protocol support for connecting and communicating with I2C-compatible devices.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n