name=UART
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Universal Asynchronous Receiver/Transmitter library for Beken boards
paragraph=Provides UART serial communication capabilities for asynchronous data transmission between devices.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n