name=Blink
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Blink example library for Beken boards
paragraph=Simple example demonstrating basic GPIO control by blinking an LED connected to a digital pin.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n