name=BLE
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Bluetooth Low Energy library for Beken boards
paragraph=Provides Bluetooth Low Energy communication capabilities for Beken microcontrollers supporting peripheral, central, client and server roles.
category=Communication
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n