#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


WRAPPER_HEADER = "// Auto-generated by bk_prepare_core.py.\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare sketch-specific core wrappers for Arduino IDE/CLI builds.")
    parser.add_argument("--core-path", required=True)
    parser.add_argument("--project-name", required=True)
    parser.add_argument("--sketch-path", required=True)
    return parser.parse_args()


def build_wrapper_text(project_name: str, sketch_path: str) -> str:
    return (
        WRAPPER_HEADER
        + "// Keep sketch entrypoints inside core.a so staged Arduino builds retain\n"
        + "// the native bk_idk link semantics.\n"
        + f"// sketch-path: {sketch_path}\n"
        + '#include "Arduino.h"\n\n'
        + f'#include "{project_name}.cpp"\n'
    )


def remove_stale_wrappers(core_path: Path, wrapper_path: Path) -> None:
    for stale in list(core_path.glob("GeneratedSketch_*.cpp")):
        if stale == wrapper_path:
            continue
        try:
            if not stale.exists():
                continue
            contents = stale.read_text(encoding="utf-8")
        except OSError:
            continue
        if not contents.startswith(WRAPPER_HEADER):
            continue
        try:
            stale.unlink(missing_ok=True)
        except OSError:
            continue


def main() -> int:
    args = parse_args()
    core_path = Path(args.core_path).resolve()
    core_path.mkdir(parents=True, exist_ok=True)

    sketch_key = str(Path(args.sketch_path).resolve())
    digest = hashlib.sha1(sketch_key.encode("utf-8")).hexdigest()[:16]
    wrapper_name = f"GeneratedSketch_{digest}.cpp"
    wrapper_path = core_path / wrapper_name

    remove_stale_wrappers(core_path, wrapper_path)

    wrapper_path.write_text(
        build_wrapper_text(args.project_name, sketch_key),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
