name=SPI
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Serial Peripheral Interface library for Beken boards
paragraph=Provides Serial Peripheral Interface (SPI) communication protocol support for high-speed full-duplex communication with SPI-compatible devices.
category=Examples
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n