name=ADC
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=Analog to Digital Converter library for Beken boards
paragraph=Provides analog input capabilities for reading voltage levels on ADC-enabled pins of Beken microcontrollers.
category=Signal Input/Output
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n