name=DNSServer
version=2.0.0
author=Kristijan Novoselić
maintainer=Kristijan Novoselić, <kristijan.novoselic@gmail.com>
sentence=A simple DNS server.
paragraph=Simple DNS server for arduino-beken (BK7239N) SoftAP captive-portal use cases.
category=Communication
url=
architectures=bk7239n
depends=WiFi
