#!/usr/bin/env python3

from __future__ import annotations

import os
from pathlib import Path


CORE_SOURCE_MAP: dict[str, str] = {
    "ADC.cpp": "components/arduino-beken-core/src/ADC.cpp",
    "Arduino.cpp": "components/arduino-beken-core/src/Arduino.cpp",
    "Common.cpp": "components/arduino-beken-core/src/Common.cpp",
    "GeneratedSketch.cpp": "components/arduino-beken-core/src/GeneratedSketch.cpp",
    "GeneratedSketchC.c": "components/arduino-beken-core/src/GeneratedSketchC.c",
    "GeneratedSketchCpp.cpp": "components/arduino-beken-core/src/GeneratedSketchCpp.cpp",
    "HardwareSerial.cpp": "components/arduino-beken-core/src/HardwareSerial.cpp",
    "HardwareTimer.cpp": "components/arduino-beken-core/src/HardwareTimer.cpp",
    "IPAddress.cpp": "components/arduino-beken-core/include/api/IPAddress.cpp",
    "Print.cpp": "components/arduino-beken-core/src/Print.cpp",
    "PWM.cpp": "components/arduino-beken-core/src/PWM.cpp",
    "SPI.cpp": "components/arduino-beken-core/src/SPI.cpp",
    "SketchDefaults.cpp": "components/arduino-beken-core/src/SketchDefaults.cpp",
    "String.cpp": "components/arduino-beken-core/src/String.cpp",
    "Stream.cpp": "components/arduino-beken-core/src/Stream.cpp",
    "StreamString.cpp": "components/arduino-beken-core/src/StreamString.cpp",
    "Ticker.cpp": "components/arduino-beken-core/src/Ticker.cpp",
    "Wire.cpp": "components/arduino-beken-core/src/Wire.cpp",
    "WMath.cpp": "components/arduino-beken-core/src/WMath.cpp",
    "arduino_base64.cpp": "components/arduino-beken-core/src/arduino_base64.cpp",
    "cencode.c": "components/arduino-beken-core/src/cencode.c",
    "init_stub.c": "components/arduino-beken-main/init_stub.c",
    "main.c": "components/arduino-beken-main/main.c",
    "wiring_digital.cpp": "components/arduino-beken-core/src/wiring_digital.cpp",
}

CORE_HEADER_MAP: dict[str, str] = {
    "ADC.h": "components/arduino-beken-core/include/ADC.h",
    "Arduino.h": "components/arduino-beken-core/include/Arduino.h",
    "Client.h": "components/arduino-beken-core/include/Client.h",
    "HardwareSerial.h": "components/arduino-beken-core/include/HardwareSerial.h",
    "HardwareTimer.h": "components/arduino-beken-core/include/HardwareTimer.h",
    "IPAddress.h": "components/arduino-beken-core/include/IPAddress.h",
    "Print.h": "components/arduino-beken-core/include/api/Print.h",
    "Printable.h": "components/arduino-beken-core/include/api/Printable.h",
    "Server.h": "components/arduino-beken-core/include/Server.h",
    "SPI.h": "components/arduino-beken-core/include/SPI.h",
    "ArduinoString.h": "components/arduino-beken-core/include/api/ArduinoString.h",
    "Stream.h": "components/arduino-beken-core/include/api/Stream.h",
    "StreamString.h": "components/arduino-beken-core/include/StreamString.h",
    "Ticker.h": "components/arduino-beken-core/include/Ticker.h",
    "Udp.h": "components/arduino-beken-core/include/Udp.h",
    "Wire.h": "components/arduino-beken-core/include/Wire.h",
    "arduino_base64.h": "components/arduino-beken-core/include/arduino_base64.h",
    "bk_idk_log.h": "components/arduino-beken-core/include/bk_idk_log.h",
    "cencode.h": "components/arduino-beken-core/include/cencode.h",
    "api/ArduinoAPI.h": "components/arduino-beken-core/include/api/ArduinoAPI.h",
    "api/Client.h": "components/arduino-beken-core/include/api/Client.h",
    "api/Common.h": "components/arduino-beken-core/include/api/Common.h",
    "api/IPAddress.h": "components/arduino-beken-core/include/api/IPAddress.h",
    "api/Print.h": "components/arduino-beken-core/include/api/Print.h",
    "api/Printable.h": "components/arduino-beken-core/include/api/Printable.h",
    "api/Server.h": "components/arduino-beken-core/include/api/Server.h",
    "api/Stream.h": "components/arduino-beken-core/include/api/Stream.h",
    "api/ArduinoString.h": "components/arduino-beken-core/include/api/ArduinoString.h",
    "api/Udp.h": "components/arduino-beken-core/include/api/Udp.h",
}

STAGED_CORE_PRUNED_FILES = {
    "GeneratedSketch.cpp",
    "init_stub.c",
    "main.c",
}


def wrapper_text(include_target: str) -> str:
    return (
        "// Auto-generated by tools/generate_core_wrappers.py.\n"
        "// Edit the implementation under components/, not this wrapper.\n"
        f'#include "{include_target}"\n'
    )


def generate_core_wrappers(project_root: Path, core_dir: Path, excluded: set[str] | None = None) -> list[Path]:
    core_dir.mkdir(parents=True, exist_ok=True)
    excluded = excluded or set()

    written: list[Path] = []
    for mapping in (CORE_SOURCE_MAP, CORE_HEADER_MAP):
        for wrapper_name, include_target in sorted(mapping.items()):
            if wrapper_name in excluded:
                continue
            source_path = project_root / include_target
            if not source_path.exists():
                raise FileNotFoundError(f"Core wrapper source not found: {source_path}")

            wrapper_path = core_dir / wrapper_name
            wrapper_path.parent.mkdir(parents=True, exist_ok=True)
            relative_include = os.path.relpath(source_path, wrapper_path.parent).replace(os.sep, "/")
            wrapper_path.write_text(wrapper_text(relative_include), encoding="utf-8")
            written.append(wrapper_path)

    api_root = project_root / "components" / "arduino-beken-core" / "include" / "api"
    if api_root.exists():
        for source_path in sorted(api_root.rglob("*.h")):
            wrapper_name = source_path.relative_to(api_root).as_posix()
            wrapper_path = core_dir / "api" / wrapper_name
            if wrapper_path in written:
                continue
            relative_include = os.path.relpath(source_path, wrapper_path.parent).replace(os.sep, "/")
            wrapper_path.parent.mkdir(parents=True, exist_ok=True)
            wrapper_path.write_text(wrapper_text(relative_include), encoding="utf-8")
            written.append(wrapper_path)

    return written
