#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from pathlib import Path


FUNCTION_DEF_RE = re.compile(
    r"^\s*(?!if\b|for\b|while\b|switch\b|catch\b|else\b|do\b)(?:[\w:\<\>\~\*&\s]+?\s+)?"
    r"(?P<name>[A-Za-z_]\w*)\s*\((?P<params>[^;{}]*)\)\s*"
    r"(?P<suffix>(?:const\b\s*)?(?:noexcept\b\s*)?(?:->\s*[^{}]+)?)\s*\{$",
    re.MULTILINE,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare an Arduino sketch for the bk_idk build.")
    parser.add_argument("--sketch", required=True, help="Path to a sketch directory, .ino sketch, or .cpp sketch")
    parser.add_argument("--output", required=True, help="Generated .cpp output path")
    parser.add_argument("--extra-c-output", help="Generated .c output path for extra sketch C sources")
    parser.add_argument("--extra-cpp-output", help="Generated .cpp output path for extra sketch C++ sources")
    return parser.parse_args()


def resolve_sketch_sources(sketch: Path) -> tuple[list[Path], bool]:
    if sketch.is_dir():
        sketch_dir = sketch
        primary_ino = sketch_dir / f"{sketch_dir.name}.ino"
        if primary_ino.exists():
            ino_files = [primary_ino] + sorted(path for path in sketch_dir.glob("*.ino") if path != primary_ino)
            return ino_files, True

        cpp_files = sorted(sketch_dir.glob("*.cpp"))
        if len(cpp_files) == 1:
            return cpp_files, False
        if cpp_files:
            raise SystemExit(
                f"Sketch directory contains multiple .cpp files but no primary .ino: {sketch_dir}"
            )
        raise SystemExit(
            f"Sketch directory must contain {sketch_dir.name}.ino or a single .cpp file: {sketch_dir}"
        )

    if sketch.suffix == ".ino":
        primary_ino = sketch
        ino_files = [primary_ino] + sorted(path for path in sketch.parent.glob("*.ino") if path != primary_ino)
        return ino_files, True

    if sketch.suffix == ".cpp":
        return [sketch], False

    raise SystemExit(f"Unsupported sketch input: {sketch}")


def resolve_extra_sources(sketch: Path, is_ino_sketch: bool) -> list[Path]:
    if not is_ino_sketch:
        return []

    sketch_dir = sketch if sketch.is_dir() else sketch.parent
    extra_sources = list(sketch_dir.glob("*.c")) + list(sketch_dir.glob("*.cpp"))
    return sorted(path for path in extra_sources if path.is_file())


def generate_function_prototypes(source: str) -> str:
    prototypes: list[str] = []
    candidate_lines: list[str] = []
    paren_depth = 0
    brace_depth = 0

    for raw_line in source.splitlines():
        line = raw_line.strip()

        if brace_depth == 0:
            if not candidate_lines and not line:
                pass
            elif not candidate_lines and line.startswith(("#", "//", "/*", "*")):
                pass
            else:
                candidate_lines.append(raw_line)

            candidate = "\n".join(candidate_lines).strip()
            if candidate and "{" in candidate and paren_depth == 0:
                flattened = " ".join(part.strip() for part in candidate_lines)
                if flattened.endswith("{"):
                    match = FUNCTION_DEF_RE.match(flattened)
                    if match:
                        name = match.group("name")
                        if name not in {"setup", "loop"}:
                            signature = flattened[:-1].strip()
                            prototypes.append(f"{signature};")
                candidate_lines = []

        paren_depth += raw_line.count("(") - raw_line.count(")")
        brace_depth += raw_line.count("{") - raw_line.count("}")

        if brace_depth != 0:
            candidate_lines = []

    unique: list[str] = []
    seen: set[str] = set()
    for prototype in prototypes:
        if prototype not in seen:
            seen.add(prototype)
            unique.append(prototype)
    return "\n".join(unique)


def write_extra_source(output_path: Path | None, sources: list[Path]) -> None:
    if output_path is None:
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by sketch_prep.py\n"]
    for source_path in sources:
        lines.append(f'#include "{source_path.as_posix()}"\n')
    output_path.write_text("".join(lines), encoding="utf-8")


def prepare_sketch(
    sketch: Path,
    output_path: Path,
    extra_c_output: Path | None = None,
    extra_cpp_output: Path | None = None,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    sketch_sources, is_ino_sketch = resolve_sketch_sources(sketch)
    extra_sources = resolve_extra_sources(sketch, is_ino_sketch)
    write_extra_source(extra_c_output, [path for path in extra_sources if path.suffix == ".c"])
    write_extra_source(extra_cpp_output, [path for path in extra_sources if path.suffix == ".cpp"])

    prefix = ""
    body_parts: list[str] = []

    if is_ino_sketch:
        prefix = '#include <Arduino.h>\n\n' + prefix

    for source_path in sketch_sources:
        body_parts.append(f"// Source: {source_path.name}\n")
        body_parts.append(source_path.read_text(encoding="utf-8").rstrip())
        body_parts.append("\n\n")

    body = "".join(body_parts).rstrip() + "\n"
    if is_ino_sketch:
        prototypes = generate_function_prototypes(body)
        if prototypes:
            prefix += prototypes + "\n\n"

    output_path.write_text(prefix + body, encoding="utf-8")
    return output_path


def main() -> int:
    args = parse_args()
    sketch_path = Path(args.sketch).resolve()
    output_path = Path(args.output).resolve()
    extra_c_output = Path(args.extra_c_output).resolve() if args.extra_c_output else None
    extra_cpp_output = Path(args.extra_cpp_output).resolve() if args.extra_cpp_output else None

    if not sketch_path.exists():
        raise SystemExit(f"Sketch not found: {sketch_path}")

    prepare_sketch(sketch_path, output_path, extra_c_output, extra_cpp_output)
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
