name=WiFi
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=WiFi library for Beken boards
paragraph=Provides WiFi connectivity capabilities for Beken microcontrollers supporting station and access point modes.
category=Communication
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n