name=WiFi
version=1.0.0
author=Haoyuan Jiang
maintainer=Haoyuan Jiang <haoyuan.jiang@bekencorp.com>
sentence=WiFi library for Beken boards
paragraph=Provides WiFi connectivity for Beken microcontrollers (STA, AP, scan, TCP/UDP, server, multi-AP, events) using bk_wifi and lwIP.
category=Communication
url=https://github.com/bekencorp/arduino-beken
architectures=bk7239n
