name=PubSubClient
version=2.8
author=Nick O'Leary <nick.oleary@gmail.com>
maintainer=BK-IDK
sentence=A client library for MQTT messaging.
paragraph=MQTT client for arduino-beken (BK7239N), based on Nick O'Leary's PubSubClient. Supports MQTT 3.1.1 (and optional 3.1) over WiFiClient.
category=Communication
url=http://pubsubclient.knolleary.net
architectures=bk7239n
depends=WiFi
